services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_vol:/var/lib/postgresql/data

volumes:
  db_vol:
